### ISSUE TITLE
ADC with rate of more than 500KSPS

### ISSUE THREAD

**Issue by epsi1on** [FilipDominec/rp2daq#20]
Hi,
Is it possible to use ADC with resolution 8 bit/sample and more sample rate, like 750 ksps?
Thanks

**Comment by FilipDominec** [comment]
Hi, it is not possible with the built-in ADC - you would have to get an external one and get its digitized data with some efficient way, such as PIO+DMA. 

With this approach I am planning to make the 100 Msps oscilloscope, but still not having free time to do it.
