### ISSUE TITLE
Edge Detection

### ISSUE THREAD

**Issue by epsi1on** [FilipDominec/rp2daq#8]
Hi,
How does the Edge Detection works? is it a trigger which tells the ADC to when take samples?
I would be thankful if you give me some info about it's logic.
Thank you

**Comment by FilipDominec** [comment]
It is a separate interrupt handler for a leading/falling edge on a user-determined digital GPIO. 

If ADC is set up to wait for trigger event, the handler immediately executes short, jitter-free routine that starts an ADC block acquisition within some 4 μs from the incoming edge.

The binary interface has thus changed; if you intend to use your C# program with hard-coded commands, please see https://github.com/FilipDominec/rp2daq/blob/main/include/adc_builtin.c#L49 struct to add the new options into your ADC-initiating binary sequence. 

Feel free to ask if anything fails.

BTW would you find it useful if there was an optional force-trigger timeout?
